
platform :ios, ‘8.0’

target:"StudentClient" do

pod 'Reachability', '3.2'

pod 'AFNetworking', '3.1.0'

pod 'SDWebImage', '3.7.6'

pod 'Masonry', '1.0.1'

pod 'MJExtension', '3.0.13'

pod 'MJRefresh', '3.1.12'

pod 'FMDB', '2.6.2'

pod 'DZNEmptyDataSet', '1.8.1'

pod 'JTNavigationController', '1.0.1'

pod 'LCTabBarController', '1.3.3'

pod 'Bugtags', '2.0.0'

pod 'ReactiveCocoa', '2.5'

pod 'YYKit', '1.0.9'

pod 'SVProgressHUD', '2.0.3'

pod 'WebViewJavascriptBridge', '5.0.5'

pod 'SDCycleScrollView', '1.65'

pod 'BBCyclingLabel', '1.0.1'

pod 'IQKeyboardManager', '3.3.7'

pod 'UITableView+FDTemplateLayoutCell', '1.4'

pod 'MWPhotoBrowser', '2.1.2'

pod 'JSBadgeView', '1.4.1'

pod 'UIView+MGBadgeView', '0.0.1'

pod 'JTMaterialSwitch', '1.1'

pod 'ZFPlayer', '2.0.2'

pod 'NJKWebViewProgress', '0.2.3'

pod 'SZTextView', '1.2.2'

end


